# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-09 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldWordCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_words', models.IntegerField(default=0)),
                ('valid', models.BooleanField(default=False)),
                ('field', models.CharField(db_index=True, max_length=64)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='KeyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(default=None, null=True)),
                ('field', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('nl-nl', 'Dutch (The Netherlands)'), ('en-nl', 'English (The Netherlands)'), ('nl-be', 'Dutch (Belgium)'), ('fr-be', 'French (Belgium)'), ('en-be', 'English (Belgium)'), ('en-pl', 'English (Poland)'), ('pl-pl', 'Polish')], db_index=True, max_length=5)),
                ('value', models.TextField(blank=True)),
                ('edited', models.BooleanField(default=False)),
                ('fuzzy', models.BooleanField(default=False)),
                ('digest', models.CharField(db_index=True, max_length=40)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='ModelWordCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_words', models.IntegerField(default=0)),
                ('valid', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='keyvalue',
            unique_together=set([('language', 'content_type', 'field', 'object_id', 'digest')]),
        ),
        migrations.AlterUniqueTogether(
            name='fieldwordcount',
            unique_together=set([('content_type', 'field')]),
        ),
    ]
