# Generated by Django 2.2.16 on 2020-09-17 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datatrans', '0005_auto_20181211_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelwordcount',
            name='content_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
