# Generated by Django 3.0.10 on 2022-03-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datatrans", "0006_auto_20200917_0122"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyvalue",
            name="language",
            field=models.CharField(
                choices=[
                    ("en-pl", "English (Poland)"),
                    ("pl-pl", "Polish"),
                    ("uk-pl", "Ukrainian (Poland)"),
                ],
                db_index=True,
                max_length=5,
            ),
        ),
    ]
