# Generated by Django 3.0.10 on 2022-12-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datatrans", "0007_auto_20220315_1139"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyvalue",
            name="language",
            field=models.CharField(
                choices=[("en-pl", "English (Poland)"), ("pl-pl", "Polish")],
                db_index=True,
                max_length=5,
            ),
        ),
    ]
